### ISSUE TITLE
Can you share your article's code ?

### ISSUE THREAD

**Issue by ross-Hr** [jodumagpi/Xray-ObjSep-v1#1]
Hi，can you share the 'Evaluating GAN-Based Image Augmentation for Threat Detection in Large-Scale Xray Security Images' source code ?

**Comment by jodumagpi** [comment]
Hi! That project was a straightforward investigation of the impact of using GAN-based techniques to enlarge the dataset. You can look up implementations such as the ones listed in this [repo](https://github.com/eriklindernoren/PyTorch-GAN) to use to generate fake threat objects. Then, you can use established frameworks such as [this](https://github.com/facebookresearch/detectron2) to train your detection model.
