### ISSUE TITLE
about .pth 

### ISSUE THREAD

**Issue by barbarianxs** [jodumagpi/Xray-ObjSep-v1#2]
can you provide faster_rcnn_091321.pth this file? i can't find it

**Comment by jodumagpi** [comment]
hi! that is the file for your trained model. you have to train a faster rcnn network using pytorch framework to generate that file.

**Comment by barbarianxs** [comment]
Hi,very glad that you can reply to me so soon! I'm just getting started in the field of deep learning. To tell the truth, my elder martial brother and I think there is something wrong with the load function you wrote, as shown in the figure below. I put it under / connent / PTH file, but the error is unable to read the modified file. Do you know why?
![image](https://user-images.githubusercontent.com/85329582/160636655-4e08282c-0ca8-4c43-8def-f6ea5010574a.png)
![image](https://user-images.githubusercontent.com/85329582/160637559-5b469702-c9ee-4d9a-8f03-2401ed548d76.png)
![image](https://user-images.githubusercontent.com/85329582/160637947-1da0b0bb-4723-49ea-aef1-b1de21a14540.png)

**Comment by jodumagpi** [comment]
Hi! Have you tried giving the full path? Can you provide a screenshot of your config (.yaml) file?

**Comment by barbarianxs** [comment]
> Hi! Have you tried giving the full path? Can you provide a screenshot of your config (.yaml) file?

Thank you, i have solved this problem,but a new one comes up.
![image](https://user-images.githubusercontent.com/85329582/161088455-fabcb6e3-121b-41db-8340-53c08b3f0163.png)
![@UMGCG 4N2661(A2KMCW}VC](https://user-images.githubusercontent.com/85329582/161088644-db981a9a-8658-4a96-abe7-bab2f3a2d8bb.png)
i try to run the code, do you know how to solve it?

**Comment by jodumagpi** [comment]
How did you solve the problem? It seems like you did not change the path in the config file, right?

Regarding this new problem, it says in the error log that your file seems to not have been properly saved.

**Comment by barbarianxs** [comment]
> How did you solve the problem? It seems like you did not change the path in the config file, right?
> 
> Regarding this new problem, it says in the error log that your file seems to not have been properly saved.

The previous problem was because I wrote the wrong path. Can I ask a stupid question, how to train what you said before PTH file? I've just come into this field. The PTH file here is incorrect. I downloaded a PTH file directly from the official website and changed its name, so the parameters are incorrect and an error is reported.

**Comment by jodumagpi** [comment]
You can refer to [this repository](https://github.com/facebookresearch/detectron2) for training object detection models and [this repository](https://github.com/qubvel/segmentation_models.pytorch) for training segmentation models.
